name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Cache Haxe
      uses: actions/cache@v3
      with:
        path: ~/haxe
        key: ${{ runner.os }}-haxe

    - name: Install Lix
      uses: lix-pm/setup-lix@master

    - name: Install Haxe Libraries
      run: lix download

    - name: Build
      run: haxe build.hxml

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.5
      with:
        # Path of the directory containing the static assets.
        path: bin # default is _site/
        # Duration after which artifact will expire in days.
        # retention-days: # optional, default is 1

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1